package cn.insurance.model;

import java.util.Date;


/**
 * TbAccount generated by MyEclipse - Hibernate Tools
 */

public class TbAccount  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Integer intPartmentId;
     private Double dbeResidual;
     private String strMoneyType;
     private Integer intIsSonUse;
     private Integer intPayTypeId;
     private Date dteStartTimeToNoPay;
     private Double dbeNeedMessage;
     private Integer intAcceptDays;
     private Double dbeAcceptMaxMoney;
     private Integer intAccountState;
     
     private Double dbeAddCount ;

    // Constructors

    /** default constructor */
    public TbAccount() {
    }

	/** minimal constructor */
    public TbAccount(Integer id) {
        this.id = id;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getIntPartmentId() {
        return this.intPartmentId;
    }
    
    public void setIntPartmentId(Integer intPartmentId) {
        this.intPartmentId = intPartmentId;
    }

    public Double getDbeResidual() {
        return this.dbeResidual;
    }
    
    public void setDbeResidual(Double dbeResidual) {
        this.dbeResidual = dbeResidual;
    }

    public String getStrMoneyType() {
        return this.strMoneyType;
    }
    
    public void setStrMoneyType(String strMoneyType) {
        this.strMoneyType = strMoneyType;
    }


    public Integer getIntPayTypeId() {
        return this.intPayTypeId;
    }
    
    public void setIntPayTypeId(Integer intPayTypeId) {
        this.intPayTypeId = intPayTypeId;
    }

    public Date getDteStartTimeToNoPay() {
        return this.dteStartTimeToNoPay;
    }
    
    public void setDteStartTimeToNoPay(Date dteStartTimeToNoPay) {
        this.dteStartTimeToNoPay = dteStartTimeToNoPay;
    }

    public Double getDbeNeedMessage() {
        return this.dbeNeedMessage;
    }
    
    public void setDbeNeedMessage(Double dbeNeedMessage) {
        this.dbeNeedMessage = dbeNeedMessage;
    }

    public Integer getIntAcceptDays() {
        return this.intAcceptDays;
    }
    
    public void setIntAcceptDays(Integer intAcceptDays) {
        this.intAcceptDays = intAcceptDays;
    }

    public Double getDbeAcceptMaxMoney() {
        return this.dbeAcceptMaxMoney;
    }
    
    public void setDbeAcceptMaxMoney(Double dbeAcceptMaxMoney) {
        this.dbeAcceptMaxMoney = dbeAcceptMaxMoney;
    }

    public Integer getIntAccountState() {
        return this.intAccountState;
    }
    
    public void setIntAccountState(Integer intAccountState) {
        this.intAccountState = intAccountState;
    }

	public Double getDbeAddCount() {
		return dbeAddCount;
	}

	public void setDbeAddCount(Double dbeAddCount) {
		this.dbeAddCount = dbeAddCount;
	}

	public Integer getIntIsSonUse() {
		return intIsSonUse;
	}

	public void setIntIsSonUse(Integer intIsSonUse) {
		this.intIsSonUse = intIsSonUse;
	}
   








}