package cn.insurance.model;



/**
 * TbUseAdjustFee generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings("serial")
public class TbAdjustFee  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Integer intPartmentId;
     private Double dbeChinaStandard;
     private Double dbeOtherStandard;


    // Constructors

    /** default constructor */
    public TbAdjustFee() {
    }

	/** minimal constructor */
    public TbAdjustFee(Integer id) {
        this.id = id;
    }
    

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getIntPartmentId() {
        return this.intPartmentId;
    }
    
    public void setIntPartmentId(Integer intPartmentId) {
        this.intPartmentId = intPartmentId;
    }

	public Double getDbeChinaStandard() {
		return dbeChinaStandard;
	}

	public void setDbeChinaStandard(Double dbeChinaStandard) {
		this.dbeChinaStandard = dbeChinaStandard;
	}

	public Double getDbeOtherStandard() {
		return dbeOtherStandard;
	}

	public void setDbeOtherStandard(Double dbeOtherStandard) {
		this.dbeOtherStandard = dbeOtherStandard;
	}








}