package cn.insurance.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;


/**
 * TbBill generated by MyEclipse - Hibernate Tools
 */

public class TbBill  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String strBillNumber ;
     private String strBillName ;
     private String strCompanyName;
     private Integer intKindId;
     private Date dteApplyDate;
     private String strPartmentName;
     private Integer intPartmentId;
     private String strSignatoryName;
     private String strDragoman;
     private String strPhoneNumber;
     private String strFax;
     private Integer intTeamType;
     private String strTeamNumber;
     private Integer intTravelProperty;
     private String strTravelRold;
     private Integer intChinaTravelerNumber;
     private Integer intOtherTravelerNumber;
     private Double dbeChinaFee;
     private Double dbeOtherFee;
     private Double dbeAllFee;
     private Date dteStartTime;
     private Date dteEndTime;
     private Integer intTravelType;
     private Integer intIsHasHighDanger;
     private Integer intApplyUserId;
     private Integer intPayType;
     private Integer intBillStateId;
     private Integer intNBFeeType;
     private Integer intWBFeeType;
     
     
     private String strFileUrl ;
     	
     private int intIsSureByZs ;
     
     private Integer intBeiAnReason ;
     
     private Integer intIsAddTraveler ;
     
     private Integer intIsPay ;
     
     private String strReturnReason ;
     
     private int intIsPeiKuan ;
     
     private TbBillSureInfo tbBillSureInfo ;
     
     /*对应的游客列表*/
     private List<TbTravelerInfo> tbTravelerInfoList = new ArrayList<TbTravelerInfo>() ;
     
     /*申请该保单的部门*/
     private TbPartment tbPartment ;
     
     /*保险种类*/
     private String strKindName ;
    // Constructors
     
     //确认信息
     private List<TbBillSureInfo> sureInfoList = new ArrayList<TbBillSureInfo>() ;
     
     
     private String strSureUserName ;
     
     private Date dteSureTime ;
     
     /*保单的赔款情况*/
     private TbPeiKuan tbPeiKuan ;
     
     private String md5CheckCode ;
     
     
    /** default constructor */
    public TbBill() {
    }

	/** minimal constructor */
    public TbBill(Integer id) {
        this.id = id;
    }


   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getStrCompanyName() {
        return this.strCompanyName;
    }
    
    public void setStrCompanyName(String strCompanyName) {
        this.strCompanyName = strCompanyName;
    }

    public Integer getIntKindId() {
        return this.intKindId;
    }
    
    public void setIntKindId(Integer intKindId) {
        this.intKindId = intKindId;
    }

    public Date getDteApplyDate() {
        return this.dteApplyDate;
    }
    
    public void setDteApplyDate(Date dteApplyDate) {
        this.dteApplyDate = dteApplyDate;
    }

    public String getStrPartmentName() {
        return this.strPartmentName;
    }
    
    public void setStrPartmentName(String strPartmentName) {
        this.strPartmentName = strPartmentName;
    }

    public Integer getIntPartmentId() {
        return this.intPartmentId;
    }
    
    public void setIntPartmentId(Integer intPartmentId) {
        this.intPartmentId = intPartmentId;
    }

    public String getStrSignatoryName() {
        return this.strSignatoryName;
    }
    
    public void setStrSignatoryName(String strSignatoryName) {
        this.strSignatoryName = strSignatoryName;
    }

    public String getStrDragoman() {
        return this.strDragoman;
    }
    
    public void setStrDragoman(String strDragoman) {
        this.strDragoman = strDragoman;
    }

    public String getStrPhoneNumber() {
        return this.strPhoneNumber;
    }
    
    public void setStrPhoneNumber(String strPhoneNumber) {
        this.strPhoneNumber = strPhoneNumber;
    }

    public String getStrFax() {
        return this.strFax;
    }
    
    public void setStrFax(String strFax) {
        this.strFax = strFax;
    }


    public String getStrTeamNumber() {
        return this.strTeamNumber;
    }
    
    public void setStrTeamNumber(String strTeamNumber) {
        this.strTeamNumber = strTeamNumber;
    }


    public String getStrTravelRold() {
        return this.strTravelRold;
    }
    
    public void setStrTravelRold(String strTravelRold) {
        this.strTravelRold = strTravelRold;
    }

    public Integer getIntChinaTravelerNumber() {
        return this.intChinaTravelerNumber;
    }
    
    public void setIntChinaTravelerNumber(Integer intChinaTravelerNumber) {
        this.intChinaTravelerNumber = intChinaTravelerNumber;
    }

    public Integer getIntOtherTravelerNumber() {
        return this.intOtherTravelerNumber;
    }
    
    public void setIntOtherTravelerNumber(Integer intOtherTravelerNumber) {
        this.intOtherTravelerNumber = intOtherTravelerNumber;
    }

    public Double getDbeChinaFee() {
        return this.dbeChinaFee;
    }
    
    public void setDbeChinaFee(Double dbeChinaFee) {
        this.dbeChinaFee = dbeChinaFee;
    }

    public Double getDbeOtherFee() {
        return this.dbeOtherFee;
    }
    
    public void setDbeOtherFee(Double dbeOtherFee) {
        this.dbeOtherFee = dbeOtherFee;
    }

    public Double getDbeAllFee() {
        return this.dbeAllFee;
    }
    
    public void setDbeAllFee(Double dbeAllFee) {
        this.dbeAllFee = dbeAllFee;
    }

    public Date getDteStartTime() {
        return this.dteStartTime;
    }
    
    public void setDteStartTime(Date dteStartTime) {
        this.dteStartTime = dteStartTime;
    }

    public Date getDteEndTime() {
        return this.dteEndTime;
    }
    
    public void setDteEndTime(Date dteEndTime) {
        this.dteEndTime = dteEndTime;
    }

    public Integer getIntTravelType() {
        return this.intTravelType;
    }
    
    public void setIntTravelType(Integer intTravelType) {
        this.intTravelType = intTravelType;
    }


    public Integer getIntIsHasHighDanger() {
		return intIsHasHighDanger;
	}

	public void setIntIsHasHighDanger(Integer intIsHasHighDanger) {
		this.intIsHasHighDanger = intIsHasHighDanger;
	}

	public Integer getIntTeamType() {
		return intTeamType;
	}

	public void setIntTeamType(Integer intTeamType) {
		this.intTeamType = intTeamType;
	}

	public Integer getIntTravelProperty() {
		return intTravelProperty;
	}

	public void setIntTravelProperty(Integer intTravelProperty) {
		this.intTravelProperty = intTravelProperty;
	}


	public TbPartment getTbPartment() {
		return tbPartment;
	}

	public void setTbPartment(TbPartment tbPartment) {
		this.tbPartment = tbPartment;
	}

	public List<TbTravelerInfo> getTbTravelerInfoList() {
		return tbTravelerInfoList;
	}

	public void setTbTravelerInfoList(List<TbTravelerInfo> tbTravelerInfoList) {
		this.tbTravelerInfoList = tbTravelerInfoList;
	}

	public Integer getIntApplyUserId() {
        return this.intApplyUserId;
    }
    
    public void setIntApplyUserId(Integer intApplyUserId) {
        this.intApplyUserId = intApplyUserId;
    }


    public Integer getIntPayType() {
        return this.intPayType;
    }
    
    public void setIntPayType(Integer intPayType) {
        this.intPayType = intPayType;
    }

    public Integer getIntBillStateId() {
        return this.intBillStateId;
    }
    
    public void setIntBillStateId(Integer intBillStateId) {
        this.intBillStateId = intBillStateId;
    }


	public String getStrBillName() {
		return strBillName;
	}

	public void setStrBillName(String strBillName) {
		this.strBillName = strBillName;
	}

	public Integer getIntIsAddTraveler() {
		return intIsAddTraveler;
	}

	public void setIntIsAddTraveler(Integer intIsAddTraveler) {
		this.intIsAddTraveler = intIsAddTraveler;
	}

	public Integer getIntIsPay() {
		return intIsPay;
	}

	public void setIntIsPay(Integer intIsPay) {
		this.intIsPay = intIsPay;
	}

	public String getStrReturnReason() {
		return strReturnReason;
	}

	public void setStrReturnReason(String strReturnReason) {
		this.strReturnReason = strReturnReason;
	}

	public List<TbBillSureInfo> getSureInfoList() {
		return sureInfoList;
	}

	public void setSureInfoList(List<TbBillSureInfo> sureInfoList) {
		this.sureInfoList = sureInfoList;
	}

	public TbBillSureInfo getTbBillSureInfo() {
		return tbBillSureInfo;
	}

	public void setTbBillSureInfo(TbBillSureInfo tbBillSureInfo) {
		this.tbBillSureInfo = tbBillSureInfo;
	}

	public String getStrFileUrl() {
		return strFileUrl;
	}

	public void setStrFileUrl(String strFileUrl) {
		this.strFileUrl = strFileUrl;
	}

	public Integer getIntBeiAnReason() {
		return intBeiAnReason;
	}

	public void setIntBeiAnReason(Integer intBeiAnReason) {
		this.intBeiAnReason = intBeiAnReason;
	}

	public String getStrBillNumber() {
		return strBillNumber;
	}

	public void setStrBillNumber(String strBillNumber) {
		this.strBillNumber = strBillNumber;
	}

	public int getIntIsPeiKuan() {
		return intIsPeiKuan;
	}

	public void setIntIsPeiKuan(int intIsPeiKuan) {
		this.intIsPeiKuan = intIsPeiKuan;
	}

	public Date getDteSureTime() {
		return dteSureTime;
	}

	public void setDteSureTime(Date dteSureTime) {
		this.dteSureTime = dteSureTime;
	}

	public String getStrSureUserName() {
		return strSureUserName;
	}

	public void setStrSureUserName(String strSureUserName) {
		this.strSureUserName = strSureUserName;
	}

	public TbPeiKuan getTbPeiKuan() {
		return tbPeiKuan;
	}

	public void setTbPeiKuan(TbPeiKuan tbPeiKuan) {
		this.tbPeiKuan = tbPeiKuan;
	}

	public int getIntIsSureByZs() {
		return intIsSureByZs;
	}

	public void setIntIsSureByZs(int intIsSureByZs) {
		this.intIsSureByZs = intIsSureByZs;
	}

	public String getStrKindName() {
		return strKindName;
	}

	public void setStrKindName(String strKindName) {
		this.strKindName = strKindName;
	}

	public String getMd5CheckCode() {
		return md5CheckCode;
	}

	public void setMd5CheckCode(String md5CheckCode) {
		this.md5CheckCode = md5CheckCode;
	}

	public Integer getIntNBFeeType() {
		return intNBFeeType;
	}

	public void setIntNBFeeType(Integer intNBFeeType) {
		this.intNBFeeType = intNBFeeType;
	}

	public Integer getIntWBFeeType() {
		return intWBFeeType;
	}

	public void setIntWBFeeType(Integer intWBFeeType) {
		this.intWBFeeType = intWBFeeType;
	}



}