package cn.insurance.model;



/**
 * TbBillState generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings("serial")
public class TbBillState  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Integer intIsLxsSure;
     private Integer intIsBxSure;
     private Integer intIsPayForFee;
     private Integer intIsHasEffective;
     private String strDesc ;

    // Constructors

    /** default constructor */
    public TbBillState() {
    }

	/** minimal constructor */
    public TbBillState(Integer id) {
        this.id = id;
    }
    
    /** full constructor */
    public TbBillState(Integer id, Integer intIsLxsSure, Integer intIsBxSure, Integer intIsPayForFee, Integer intIsHasEffective) {
        this.id = id;
        this.intIsLxsSure = intIsLxsSure;
        this.intIsBxSure = intIsBxSure;
        this.intIsPayForFee = intIsPayForFee;
        this.intIsHasEffective = intIsHasEffective;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getIntIsLxsSure() {
        return this.intIsLxsSure;
    }
    
    public void setIntIsLxsSure(Integer intIsLxsSure) {
        this.intIsLxsSure = intIsLxsSure;
    }

    public Integer getIntIsBxSure() {
        return this.intIsBxSure;
    }
    
    public void setIntIsBxSure(Integer intIsBxSure) {
        this.intIsBxSure = intIsBxSure;
    }

    public Integer getIntIsPayForFee() {
        return this.intIsPayForFee;
    }
    
    public void setIntIsPayForFee(Integer intIsPayForFee) {
        this.intIsPayForFee = intIsPayForFee;
    }

    public Integer getIntIsHasEffective() {
        return this.intIsHasEffective;
    }
    
    public void setIntIsHasEffective(Integer intIsHasEffective) {
        this.intIsHasEffective = intIsHasEffective;
    }

	public String getStrDesc() {
		return strDesc;
	}

	public void setStrDesc(String strDesc) {
		this.strDesc = strDesc;
	}
   








}