package cn.insurance.model;

import java.util.Date;


/**
 * TbBillBackup generated by MyEclipse - Hibernate Tools
 */

public class TbBillBackup  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Integer intBillId;
     private String strBillNumber;
     private String strBillName;
     private String strCompanyName;
     private Integer intKindId;
     private Integer intApplyUserId;
     private Date dteApplyDate;
     private String strPartmentName;
     private Integer intPartmentId;
     private String strSignatoryName;
     private String strDragoman;
     private String strPhoneNumber;
     private String strFax;
     private Short intTeamType;
     private String strTeamNumber;
     private Short intTravelProperty;
     private String strTravelRold;
     private Integer intChinaTravelerNumber;
     private Integer intOtherTravelerNumber;
     private Double dbeChinaFee;
     private Double dbeOtherFee;
     private Double dbeAllFee;
     private Date dteStartTime;
     private Date dteEndTime;
     private Integer intTravelType;
     private Byte intIsHasHighDanger;
     private Integer intIsAddtraveler;
     private String strFileUrl;
     private Integer intIsSureByZs;
     private Integer intPayType;
     private Integer intIsPay;
     private Integer intBeiAnReason;
     private String strReturnReason;
     private Integer intBillStateId;
     private Integer intIsPeiKuan;
     private String strSureUserName;
     private Date dteSureTime;
     private Integer intBxUpdateUserId;
     private String strBxUpdateUserName;
     private String strBxUpdateDesc;
     private Date dteBxUpdateTime;


    // Constructors

    /** default constructor */
    public TbBillBackup() {
    }

	/** minimal constructor */
    public TbBillBackup(Integer id) {
        this.id = id;
    }
    
    /** full constructor */
    public TbBillBackup(Integer id, Integer intBillId, String strBillNumber, String strBillName, String strCompanyName, Integer intKindId, Integer intApplyUserId, Date dteApplyDate, String strPartmentName, Integer intPartmentId, String strSignatoryName, String strDragoman, String strPhoneNumber, String strFax, Short intTeamType, String strTeamNumber, Short intTravelProperty, String strTravelRold, Integer intChinaTravelerNumber, Integer intOtherTravelerNumber, Double dbeChinaFee, Double dbeOtherFee, Double dbeAllFee, Date dteStartTime, Date dteEndTime, Integer intTravelType, Byte intIsHasHighDanger, Integer intIsAddtraveler, String strFileUrl, Integer intIsSureByZs, Integer intPayType, Integer intIsPay, Integer intBeiAnReason, String strReturnReason, Integer intBillStateId, Integer intIsPeiKuan, String strSureUserName, Date dteSureTime, Integer intBxUpdateUserId, String strBxUpdateUserName, String strBxUpdateDesc, Date dteBxUpdateTime) {
        this.id = id;
        this.intBillId = intBillId;
        this.strBillNumber = strBillNumber;
        this.strBillName = strBillName;
        this.strCompanyName = strCompanyName;
        this.intKindId = intKindId;
        this.intApplyUserId = intApplyUserId;
        this.dteApplyDate = dteApplyDate;
        this.strPartmentName = strPartmentName;
        this.intPartmentId = intPartmentId;
        this.strSignatoryName = strSignatoryName;
        this.strDragoman = strDragoman;
        this.strPhoneNumber = strPhoneNumber;
        this.strFax = strFax;
        this.intTeamType = intTeamType;
        this.strTeamNumber = strTeamNumber;
        this.intTravelProperty = intTravelProperty;
        this.strTravelRold = strTravelRold;
        this.intChinaTravelerNumber = intChinaTravelerNumber;
        this.intOtherTravelerNumber = intOtherTravelerNumber;
        this.dbeChinaFee = dbeChinaFee;
        this.dbeOtherFee = dbeOtherFee;
        this.dbeAllFee = dbeAllFee;
        this.dteStartTime = dteStartTime;
        this.dteEndTime = dteEndTime;
        this.intTravelType = intTravelType;
        this.intIsHasHighDanger = intIsHasHighDanger;
        this.intIsAddtraveler = intIsAddtraveler;
        this.strFileUrl = strFileUrl;
        this.intIsSureByZs = intIsSureByZs;
        this.intPayType = intPayType;
        this.intIsPay = intIsPay;
        this.intBeiAnReason = intBeiAnReason;
        this.strReturnReason = strReturnReason;
        this.intBillStateId = intBillStateId;
        this.intIsPeiKuan = intIsPeiKuan;
        this.strSureUserName = strSureUserName;
        this.dteSureTime = dteSureTime;
        this.intBxUpdateUserId = intBxUpdateUserId;
        this.strBxUpdateUserName = strBxUpdateUserName;
        this.strBxUpdateDesc = strBxUpdateDesc;
        this.dteBxUpdateTime = dteBxUpdateTime;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getIntBillId() {
        return this.intBillId;
    }
    
    public void setIntBillId(Integer intBillId) {
        this.intBillId = intBillId;
    }

    public String getStrBillNumber() {
        return this.strBillNumber;
    }
    
    public void setStrBillNumber(String strBillNumber) {
        this.strBillNumber = strBillNumber;
    }

    public String getStrBillName() {
        return this.strBillName;
    }
    
    public void setStrBillName(String strBillName) {
        this.strBillName = strBillName;
    }

    public String getStrCompanyName() {
        return this.strCompanyName;
    }
    
    public void setStrCompanyName(String strCompanyName) {
        this.strCompanyName = strCompanyName;
    }

    public Integer getIntKindId() {
        return this.intKindId;
    }
    
    public void setIntKindId(Integer intKindId) {
        this.intKindId = intKindId;
    }

    public Integer getIntApplyUserId() {
        return this.intApplyUserId;
    }
    
    public void setIntApplyUserId(Integer intApplyUserId) {
        this.intApplyUserId = intApplyUserId;
    }

    public Date getDteApplyDate() {
        return this.dteApplyDate;
    }
    
    public void setDteApplyDate(Date dteApplyDate) {
        this.dteApplyDate = dteApplyDate;
    }

    public String getStrPartmentName() {
        return this.strPartmentName;
    }
    
    public void setStrPartmentName(String strPartmentName) {
        this.strPartmentName = strPartmentName;
    }

    public Integer getIntPartmentId() {
        return this.intPartmentId;
    }
    
    public void setIntPartmentId(Integer intPartmentId) {
        this.intPartmentId = intPartmentId;
    }

    public String getStrSignatoryName() {
        return this.strSignatoryName;
    }
    
    public void setStrSignatoryName(String strSignatoryName) {
        this.strSignatoryName = strSignatoryName;
    }

    public String getStrDragoman() {
        return this.strDragoman;
    }
    
    public void setStrDragoman(String strDragoman) {
        this.strDragoman = strDragoman;
    }

    public String getStrPhoneNumber() {
        return this.strPhoneNumber;
    }
    
    public void setStrPhoneNumber(String strPhoneNumber) {
        this.strPhoneNumber = strPhoneNumber;
    }

    public String getStrFax() {
        return this.strFax;
    }
    
    public void setStrFax(String strFax) {
        this.strFax = strFax;
    }

    public Short getIntTeamType() {
        return this.intTeamType;
    }
    
    public void setIntTeamType(Short intTeamType) {
        this.intTeamType = intTeamType;
    }

    public String getStrTeamNumber() {
        return this.strTeamNumber;
    }
    
    public void setStrTeamNumber(String strTeamNumber) {
        this.strTeamNumber = strTeamNumber;
    }

    public Short getIntTravelProperty() {
        return this.intTravelProperty;
    }
    
    public void setIntTravelProperty(Short intTravelProperty) {
        this.intTravelProperty = intTravelProperty;
    }

    public String getStrTravelRold() {
        return this.strTravelRold;
    }
    
    public void setStrTravelRold(String strTravelRold) {
        this.strTravelRold = strTravelRold;
    }

    public Integer getIntChinaTravelerNumber() {
        return this.intChinaTravelerNumber;
    }
    
    public void setIntChinaTravelerNumber(Integer intChinaTravelerNumber) {
        this.intChinaTravelerNumber = intChinaTravelerNumber;
    }

    public Integer getIntOtherTravelerNumber() {
        return this.intOtherTravelerNumber;
    }
    
    public void setIntOtherTravelerNumber(Integer intOtherTravelerNumber) {
        this.intOtherTravelerNumber = intOtherTravelerNumber;
    }

    public Double getDbeChinaFee() {
        return this.dbeChinaFee;
    }
    
    public void setDbeChinaFee(Double dbeChinaFee) {
        this.dbeChinaFee = dbeChinaFee;
    }

    public Double getDbeOtherFee() {
        return this.dbeOtherFee;
    }
    
    public void setDbeOtherFee(Double dbeOtherFee) {
        this.dbeOtherFee = dbeOtherFee;
    }

    public Double getDbeAllFee() {
        return this.dbeAllFee;
    }
    
    public void setDbeAllFee(Double dbeAllFee) {
        this.dbeAllFee = dbeAllFee;
    }

    public Date getDteStartTime() {
        return this.dteStartTime;
    }
    
    public void setDteStartTime(Date dteStartTime) {
        this.dteStartTime = dteStartTime;
    }

    public Date getDteEndTime() {
        return this.dteEndTime;
    }
    
    public void setDteEndTime(Date dteEndTime) {
        this.dteEndTime = dteEndTime;
    }

    public Integer getIntTravelType() {
        return this.intTravelType;
    }
    
    public void setIntTravelType(Integer intTravelType) {
        this.intTravelType = intTravelType;
    }

    public Byte getIntIsHasHighDanger() {
        return this.intIsHasHighDanger;
    }
    
    public void setIntIsHasHighDanger(Byte intIsHasHighDanger) {
        this.intIsHasHighDanger = intIsHasHighDanger;
    }

    public Integer getIntIsAddtraveler() {
        return this.intIsAddtraveler;
    }
    
    public void setIntIsAddtraveler(Integer intIsAddtraveler) {
        this.intIsAddtraveler = intIsAddtraveler;
    }

    public String getStrFileUrl() {
        return this.strFileUrl;
    }
    
    public void setStrFileUrl(String strFileUrl) {
        this.strFileUrl = strFileUrl;
    }

    public Integer getIntIsSureByZs() {
        return this.intIsSureByZs;
    }
    
    public void setIntIsSureByZs(Integer intIsSureByZs) {
        this.intIsSureByZs = intIsSureByZs;
    }

    public Integer getIntPayType() {
        return this.intPayType;
    }
    
    public void setIntPayType(Integer intPayType) {
        this.intPayType = intPayType;
    }

    public Integer getIntIsPay() {
        return this.intIsPay;
    }
    
    public void setIntIsPay(Integer intIsPay) {
        this.intIsPay = intIsPay;
    }

    public Integer getIntBeiAnReason() {
        return this.intBeiAnReason;
    }
    
    public void setIntBeiAnReason(Integer intBeiAnReason) {
        this.intBeiAnReason = intBeiAnReason;
    }

    public String getStrReturnReason() {
        return this.strReturnReason;
    }
    
    public void setStrReturnReason(String strReturnReason) {
        this.strReturnReason = strReturnReason;
    }

    public Integer getIntBillStateId() {
        return this.intBillStateId;
    }
    
    public void setIntBillStateId(Integer intBillStateId) {
        this.intBillStateId = intBillStateId;
    }

    public Integer getIntIsPeiKuan() {
        return this.intIsPeiKuan;
    }
    
    public void setIntIsPeiKuan(Integer intIsPeiKuan) {
        this.intIsPeiKuan = intIsPeiKuan;
    }

    public String getStrSureUserName() {
        return this.strSureUserName;
    }
    
    public void setStrSureUserName(String strSureUserName) {
        this.strSureUserName = strSureUserName;
    }

    public Date getDteSureTime() {
        return this.dteSureTime;
    }
    
    public void setDteSureTime(Date dteSureTime) {
        this.dteSureTime = dteSureTime;
    }

    public Integer getIntBxUpdateUserId() {
        return this.intBxUpdateUserId;
    }
    
    public void setIntBxUpdateUserId(Integer intBxUpdateUserId) {
        this.intBxUpdateUserId = intBxUpdateUserId;
    }

    public String getStrBxUpdateUserName() {
        return this.strBxUpdateUserName;
    }
    
    public void setStrBxUpdateUserName(String strBxUpdateUserName) {
        this.strBxUpdateUserName = strBxUpdateUserName;
    }

    public String getStrBxUpdateDesc() {
        return this.strBxUpdateDesc;
    }
    
    public void setStrBxUpdateDesc(String strBxUpdateDesc) {
        this.strBxUpdateDesc = strBxUpdateDesc;
    }

    public Date getDteBxUpdateTime() {
        return this.dteBxUpdateTime;
    }
    
    public void setDteBxUpdateTime(Date dteBxUpdateTime) {
        this.dteBxUpdateTime = dteBxUpdateTime;
    }
   








}