package cn.insurance.model;

import java.util.Date;


/**
 * TbBillSureInfo generated by MyEclipse - Hibernate Tools
 */

public class TbBillSureInfo  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Integer intBillId;
     private Integer intSureType;
     private Integer intSureUserId;
     private String strSureUserName;
     private Integer intCurBillState;
     private Integer intAftBillState;
     private Date dteSureTime;
     private String strDesc;


    // Constructors

    /** default constructor */
    public TbBillSureInfo() {
    }

	/** minimal constructor */
    public TbBillSureInfo(Integer id) {
        this.id = id;
    }
    
    /** full constructor */
    public TbBillSureInfo(Integer id, Integer intBillId, Integer intSureType, Integer intSureUserId, String strSureUserName, Integer intCurBillState, Integer intAftBillState, Date dteSureTime, String strDesc) {
        this.id = id;
        this.intBillId = intBillId;
        this.intSureType = intSureType;
        this.intSureUserId = intSureUserId;
        this.strSureUserName = strSureUserName;
        this.intCurBillState = intCurBillState;
        this.intAftBillState = intAftBillState;
        this.dteSureTime = dteSureTime;
        this.strDesc = strDesc;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getIntBillId() {
        return this.intBillId;
    }
    
    public void setIntBillId(Integer intBillId) {
        this.intBillId = intBillId;
    }

    public Integer getIntSureType() {
        return this.intSureType;
    }
    
    public void setIntSureType(Integer intSureType) {
        this.intSureType = intSureType;
    }

    public Integer getIntSureUserId() {
        return this.intSureUserId;
    }
    
    public void setIntSureUserId(Integer intSureUserId) {
        this.intSureUserId = intSureUserId;
    }

    public String getStrSureUserName() {
        return this.strSureUserName;
    }
    
    public void setStrSureUserName(String strSureUserName) {
        this.strSureUserName = strSureUserName;
    }

    public Integer getIntCurBillState() {
        return this.intCurBillState;
    }
    
    public void setIntCurBillState(Integer intCurBillState) {
        this.intCurBillState = intCurBillState;
    }

    public Integer getIntAftBillState() {
        return this.intAftBillState;
    }
    
    public void setIntAftBillState(Integer intAftBillState) {
        this.intAftBillState = intAftBillState;
    }

    public Date getDteSureTime() {
        return this.dteSureTime;
    }
    
    public void setDteSureTime(Date dteSureTime) {
        this.dteSureTime = dteSureTime;
    }

    public String getStrDesc() {
        return this.strDesc;
    }
    
    public void setStrDesc(String strDesc) {
        this.strDesc = strDesc;
    }
   








}