package cn.insurance.model;



/**
 * TbBillKind generated by MyEclipse - Hibernate Tools
 */

public class TbBillKind  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String strKindName;
     private String strKindDesc;
     private String column4;
     private String column5;


    // Constructors

    /** default constructor */
    public TbBillKind() {
    }

	/** minimal constructor */
    public TbBillKind(Integer id) {
        this.id = id;
    }
    
    /** full constructor */
    public TbBillKind(Integer id, String strKindName, String strKindDesc, String column4, String column5) {
        this.id = id;
        this.strKindName = strKindName;
        this.strKindDesc = strKindDesc;
        this.column4 = column4;
        this.column5 = column5;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getStrKindName() {
        return this.strKindName;
    }
    
    public void setStrKindName(String strKindName) {
        this.strKindName = strKindName;
    }

    public String getStrKindDesc() {
        return this.strKindDesc;
    }
    
    public void setStrKindDesc(String strKindDesc) {
        this.strKindDesc = strKindDesc;
    }

    public String getColumn4() {
        return this.column4;
    }
    
    public void setColumn4(String column4) {
        this.column4 = column4;
    }

    public String getColumn5() {
        return this.column5;
    }
    
    public void setColumn5(String column5) {
        this.column5 = column5;
    }
   








}