package cn.insurance.model;



/**
 * TbLimitFeeId generated by MyEclipse - Hibernate Tools
 */

public class TbLimitFeeId  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Double dbeNeedMessage;
     private Integer intAcceptDays;
     private Double dbeAcceptMaxMoney;


    // Constructors

    /** default constructor */
    public TbLimitFeeId() {
    }

    
    /** full constructor */
    public TbLimitFeeId(Integer id, Double dbeNeedMessage, Integer intAcceptDays, Double dbeAcceptMaxMoney) {
        this.id = id;
        this.dbeNeedMessage = dbeNeedMessage;
        this.intAcceptDays = intAcceptDays;
        this.dbeAcceptMaxMoney = dbeAcceptMaxMoney;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Double getDbeNeedMessage() {
        return this.dbeNeedMessage;
    }
    
    public void setDbeNeedMessage(Double dbeNeedMessage) {
        this.dbeNeedMessage = dbeNeedMessage;
    }

    public Integer getIntAcceptDays() {
        return this.intAcceptDays;
    }
    
    public void setIntAcceptDays(Integer intAcceptDays) {
        this.intAcceptDays = intAcceptDays;
    }

    public Double getDbeAcceptMaxMoney() {
        return this.dbeAcceptMaxMoney;
    }
    
    public void setDbeAcceptMaxMoney(Double dbeAcceptMaxMoney) {
        this.dbeAcceptMaxMoney = dbeAcceptMaxMoney;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TbLimitFeeId) ) return false;
		 TbLimitFeeId castOther = ( TbLimitFeeId ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getDbeNeedMessage()==castOther.getDbeNeedMessage()) || ( this.getDbeNeedMessage()!=null && castOther.getDbeNeedMessage()!=null && this.getDbeNeedMessage().equals(castOther.getDbeNeedMessage()) ) )
 && ( (this.getIntAcceptDays()==castOther.getIntAcceptDays()) || ( this.getIntAcceptDays()!=null && castOther.getIntAcceptDays()!=null && this.getIntAcceptDays().equals(castOther.getIntAcceptDays()) ) )
 && ( (this.getDbeAcceptMaxMoney()==castOther.getDbeAcceptMaxMoney()) || ( this.getDbeAcceptMaxMoney()!=null && castOther.getDbeAcceptMaxMoney()!=null && this.getDbeAcceptMaxMoney().equals(castOther.getDbeAcceptMaxMoney()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getDbeNeedMessage() == null ? 0 : this.getDbeNeedMessage().hashCode() );
         result = 37 * result + ( getIntAcceptDays() == null ? 0 : this.getIntAcceptDays().hashCode() );
         result = 37 * result + ( getDbeAcceptMaxMoney() == null ? 0 : this.getDbeAcceptMaxMoney().hashCode() );
         return result;
   }   





}