package cn.insurance.model;

import java.util.Date;


/**
 * TbMessage generated by MyEclipse - Hibernate Tools
 */

public class TbMessage  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Date dteTime;
     private String strContent;
     private Integer intMessageType;
     private Integer intFromPartment;
     private Integer intToPartmentId;
     private Integer intIsHasShow;


    // Constructors

    /** default constructor */
    public TbMessage() {
    }

	/** minimal constructor */
    public TbMessage(Integer id) {
        this.id = id;
    }
    
    /** full constructor */
    public TbMessage(Integer id, Date dteTime, String strContent, Integer intMessageType, Integer intFromPartment, Integer intToPartmentId, Integer intIsHasShow) {
        this.id = id;
        this.dteTime = dteTime;
        this.strContent = strContent;
        this.intMessageType = intMessageType;
        this.intFromPartment = intFromPartment;
        this.intToPartmentId = intToPartmentId;
        this.intIsHasShow = intIsHasShow;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Date getDteTime() {
        return this.dteTime;
    }
    
    public void setDteTime(Date dteTime) {
        this.dteTime = dteTime;
    }

    public String getStrContent() {
        return this.strContent;
    }
    
    public void setStrContent(String strContent) {
        this.strContent = strContent;
    }

    public Integer getIntMessageType() {
        return this.intMessageType;
    }
    
    public void setIntMessageType(Integer intMessageType) {
        this.intMessageType = intMessageType;
    }

    public Integer getIntFromPartment() {
        return this.intFromPartment;
    }
    
    public void setIntFromPartment(Integer intFromPartment) {
        this.intFromPartment = intFromPartment;
    }

    public Integer getIntToPartmentId() {
        return this.intToPartmentId;
    }
    
    public void setIntToPartmentId(Integer intToPartmentId) {
        this.intToPartmentId = intToPartmentId;
    }

    public Integer getIntIsHasShow() {
        return this.intIsHasShow;
    }
    
    public void setIntIsHasShow(Integer intIsHasShow) {
        this.intIsHasShow = intIsHasShow;
    }
   








}