package cn.insurance.model;

import java.util.Date;


/**
 * TbMonthPayOutLog generated by MyEclipse - Hibernate Tools
 */

public class TbMonthPayOutLog  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Integer intMonthPayId;
     private Double dbePayNumber;
     private Date dtePayDate;
     private Integer intUserId;
     private String strUserName;
     private String strDesc;


    // Constructors

    /** default constructor */
    public TbMonthPayOutLog() {
    }

	/** minimal constructor */
    public TbMonthPayOutLog(Integer id) {
        this.id = id;
    }
    
    /** full constructor */
    public TbMonthPayOutLog(Integer id, Integer intMonthPayId, Double dbePayNumber, Date dtePayDate, Integer intUserId, String strUserName, String strDesc) {
        this.id = id;
        this.intMonthPayId = intMonthPayId;
        this.dbePayNumber = dbePayNumber;
        this.dtePayDate = dtePayDate;
        this.intUserId = intUserId;
        this.strUserName = strUserName;
        this.strDesc = strDesc;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getIntMonthPayId() {
        return this.intMonthPayId;
    }
    
    public void setIntMonthPayId(Integer intMonthPayId) {
        this.intMonthPayId = intMonthPayId;
    }

    public Double getDbePayNumber() {
        return this.dbePayNumber;
    }
    
    public void setDbePayNumber(Double dbePayNumber) {
        this.dbePayNumber = dbePayNumber;
    }

    public Date getDtePayDate() {
        return this.dtePayDate;
    }
    
    public void setDtePayDate(Date dtePayDate) {
        this.dtePayDate = dtePayDate;
    }

    public Integer getIntUserId() {
        return this.intUserId;
    }
    
    public void setIntUserId(Integer intUserId) {
        this.intUserId = intUserId;
    }

    public String getStrUserName() {
        return this.strUserName;
    }
    
    public void setStrUserName(String strUserName) {
        this.strUserName = strUserName;
    }

    public String getStrDesc() {
        return this.strDesc;
    }
    
    public void setStrDesc(String strDesc) {
        this.strDesc = strDesc;
    }
   








}