package cn.insurance.model;



/**
 * TbNote generated by MyEclipse - Hibernate Tools
 */

public class TbNote  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Integer intUserId;
     private String strDesc;


    // Constructors

    /** default constructor */
    public TbNote() {
    }

	/** minimal constructor */
    public TbNote(Integer id) {
        this.id = id;
    }
    
    /** full constructor */
    public TbNote(Integer id, Integer intUserId, String strDesc) {
        this.id = id;
        this.intUserId = intUserId;
        this.strDesc = strDesc;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getIntUserId() {
        return this.intUserId;
    }
    
    public void setIntUserId(Integer intUserId) {
        this.intUserId = intUserId;
    }

    public String getStrDesc() {
        return this.strDesc;
    }
    
    public void setStrDesc(String strDesc) {
        this.strDesc = strDesc;
    }
   








}