package cn.insurance.model;

import java.util.Date;


/**
 * TbPartment generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings("serial")
public class TbPartment  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String strPartmentName;
     private Integer intParentId;
     private String strAddress;
     private String strLicenceNumber;
     private String strPhoneNumber;
     private String strZipcode;
     private String strFax;
     private String strConnectPeople;
     private Integer intIsNeedSureBill;
     private Date dteResStartDate;
     private Date dteResEndDate;
     private String strImgUrl;
     private String strLxsBillNumber;
     private int intIsSeePartmentBill ;
     private String strPartmentType ;
     private Integer isShowHistoryBill ;
     
     /*每个部门都对应一个帐户*/
     private TbAccount tbAccount ;
     
     /*所属的旅行社旅行社*/
     private TbPartment company ; 
     
     /**该旅行社是正在使用的*/
     public static final int IS_USE_PARTMENT = 0 ;
     
     /**旅行社没有使用了（为了表示旅行社被删除了）*/
     public static final int IS_NOT_USER_PARTMENT = -1 ;
     
    // Constructors

    /** default constructor */
    public TbPartment() {
    }

	/** minimal constructor */
    public TbPartment(Integer id) {
        this.id = id;
    }
    
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getStrPartmentName() {
        return this.strPartmentName;
    }
    
    public void setStrPartmentName(String strPartmentName) {
        this.strPartmentName = strPartmentName;
    }

    public Integer getIntParentId() {
        return this.intParentId;
    }
    
    public void setIntParentId(Integer intParentId) {
        this.intParentId = intParentId;
    }

    public String getStrAddress() {
        return this.strAddress;
    }
    
    public void setStrAddress(String strAddress) {
        this.strAddress = strAddress;
    }

    public String getStrLicenceNumber() {
        return this.strLicenceNumber;
    }
    
    public void setStrLicenceNumber(String strLicenceNumber) {
        this.strLicenceNumber = strLicenceNumber;
    }

    public String getStrPhoneNumber() {
        return this.strPhoneNumber;
    }
    
    public void setStrPhoneNumber(String strPhoneNumber) {
        this.strPhoneNumber = strPhoneNumber;
    }

    public String getStrZipcode() {
        return this.strZipcode;
    }
    
    public void setStrZipcode(String strZipcode) {
        this.strZipcode = strZipcode;
    }

    public String getStrFax() {
        return this.strFax;
    }
    
    public void setStrFax(String strFax) {
        this.strFax = strFax;
    }

    public String getStrConnectPeople() {
        return this.strConnectPeople;
    }
    
    public void setStrConnectPeople(String strConnectPeople) {
        this.strConnectPeople = strConnectPeople;
    }

    public Integer getIntIsNeedSureBill() {
        return this.intIsNeedSureBill;
    }
    
    public void setIntIsNeedSureBill(Integer intIsNeedSureBill) {
        this.intIsNeedSureBill = intIsNeedSureBill;
    }

    public Date getDteResStartDate() {
        return this.dteResStartDate;
    }
    
    public void setDteResStartDate(Date dteResStartDate) {
        this.dteResStartDate = dteResStartDate;
    }

    public Date getDteResEndDate() {
        return this.dteResEndDate;
    }
    
    public void setDteResEndDate(Date dteResEndDate) {
        this.dteResEndDate = dteResEndDate;
    }

    public String getStrImgUrl() {
        return this.strImgUrl;
    }
    
    public void setStrImgUrl(String strImgUrl) {
        this.strImgUrl = strImgUrl;
    }

	public TbPartment getCompany() {
		return company;
	}

	public void setCompany(TbPartment company) {
		this.company = company;
	}

	public String getStrPartmentType() {
		return strPartmentType;
	}

	public void setStrPartmentType(String strPartmentType) {
		this.strPartmentType = strPartmentType;
	}

	public TbAccount getTbAccount() {
		return tbAccount;
	}

	public void setTbAccount(TbAccount tbAccount) {
		this.tbAccount = tbAccount;
	}

	public String getStrLxsBillNumber() {
		return strLxsBillNumber;
	}

	public void setStrLxsBillNumber(String strLxsBillNumber) {
		this.strLxsBillNumber = strLxsBillNumber;
	}

	public int getIntIsSeePartmentBill() {
		return intIsSeePartmentBill;
	}

	public void setIntIsSeePartmentBill(int intIsSeePartmentBill) {
		this.intIsSeePartmentBill = intIsSeePartmentBill;
	}

	public Integer getIsShowHistoryBill() {
		return isShowHistoryBill;
	}

	public void setIsShowHistoryBill(Integer isShowHistoryBill) {
		this.isShowHistoryBill = isShowHistoryBill;
	}
}