package cn.insurance.model;



/**
 * TbPeiKuan generated by MyEclipse - Hibernate Tools
 */

public class TbPeiKuan  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Integer intBillId;
     private Double dbePeiKuanFee;
     private String strDesc;
     
     private TbBill tbBill ;

    // Constructors

    /** default constructor */
    public TbPeiKuan() {
    }

	/** minimal constructor */
    public TbPeiKuan(Integer id) {
        this.id = id;
    }
    
    /** full constructor */
    public TbPeiKuan(Integer id, Integer intBillId, Double dbePeiKuanFee, String strDesc) {
        this.id = id;
        this.intBillId = intBillId;
        this.dbePeiKuanFee = dbePeiKuanFee;
        this.strDesc = strDesc;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getIntBillId() {
        return this.intBillId;
    }
    
    public void setIntBillId(Integer intBillId) {
        this.intBillId = intBillId;
    }

    public Double getDbePeiKuanFee() {
        return this.dbePeiKuanFee;
    }
    
    public void setDbePeiKuanFee(Double dbePeiKuanFee) {
        this.dbePeiKuanFee = dbePeiKuanFee;
    }

    public String getStrDesc() {
        return this.strDesc;
    }
    
    public void setStrDesc(String strDesc) {
        this.strDesc = strDesc;
    }

	public TbBill getTbBill() {
		return tbBill;
	}

	public void setTbBill(TbBill tbBill) {
		this.tbBill = tbBill;
	}
   








}