package cn.insurance.model;



/**
 * TbRight generated by MyEclipse - Hibernate Tools
 */

public class TbRight  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Byte right1;
     private Byte right2;


    // Constructors

    /** default constructor */
    public TbRight() {
    }

	/** minimal constructor */
    public TbRight(Integer id) {
        this.id = id;
    }
    
    /** full constructor */
    public TbRight(Integer id, Byte right1, Byte right2) {
        this.id = id;
        this.right1 = right1;
        this.right2 = right2;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Byte getRight1() {
        return this.right1;
    }
    
    public void setRight1(Byte right1) {
        this.right1 = right1;
    }

    public Byte getRight2() {
        return this.right2;
    }
    
    public void setRight2(Byte right2) {
        this.right2 = right2;
    }
   








}