package cn.insurance.model;



/**
 * TbTravelerInfo generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings("serial")
public class TbTravelerInfo  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Integer intBillId;
     private String strTravelerName;
     private String strSex ;
     private String strBirthday ;
     private String strCountry;
     private String strIndentyNumber;
     

    // Constructors

    /** default constructor */
    public TbTravelerInfo() {
    }

	/** minimal constructor */
    public TbTravelerInfo(Integer id) {
        this.id = id;
    }
    
    /** full constructor */
    public TbTravelerInfo(Integer id, Integer intBillId, String strTravelerName, String strCountry, String strIndentyNumber) {
        this.id = id;
        this.intBillId = intBillId;
        this.strTravelerName = strTravelerName;
        this.strCountry = strCountry;
        this.strIndentyNumber = strIndentyNumber;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getIntBillId() {
        return this.intBillId;
    }
    
    public void setIntBillId(Integer intBillId) {
        this.intBillId = intBillId;
    }

    public String getStrTravelerName() {
        return this.strTravelerName;
    }
    
    public void setStrTravelerName(String strTravelerName) {
        this.strTravelerName = strTravelerName;
    }

    public String getStrCountry() {
        return this.strCountry;
    }
    
    public void setStrCountry(String strCountry) {
        this.strCountry = strCountry;
    }

    public String getStrIndentyNumber() {
        return this.strIndentyNumber;
    }
    
    public void setStrIndentyNumber(String strIndentyNumber) {
        this.strIndentyNumber = strIndentyNumber;
    }

	public String getStrBirthday() {
		return strBirthday;
	}

	public void setStrBirthday(String strBirthday) {
		this.strBirthday = strBirthday;
	}

	public String getStrSex() {
		return strSex;
	}

	public void setStrSex(String strSex) {
		this.strSex = strSex;
	}









}