package cn.insurance.model;

import java.util.Date;


/**
 * TbYearPayInfo generated by MyEclipse - Hibernate Tools
 */

public class TbYearPayInfo  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Integer intAccountId;
     private Double dbeNeedFeeByYear;
     private Double dbePayFee;
     private Double dbeCurResidual;
     private Double dbeAftResidual ;
     private Date dtePayDate;
     private Date dteStartTime;
     private Date dteEndTime;
     private Integer intUser;
     private String strUserName;
     private String strDesc ;

    // Constructors

    /** default constructor */
    public TbYearPayInfo() {
    }

	/** minimal constructor */
    public TbYearPayInfo(Integer id) {
        this.id = id;
    }
    
    /** full constructor */
    public TbYearPayInfo(Integer id, Integer intAccountId, Double dbeNeedFeeByYear, Double dbePayFee, Date dtePayDate, Date dteStartTime, Date dteEndTime, Integer intUser, String strUserName) {
        this.id = id;
        this.intAccountId = intAccountId;
        this.dbeNeedFeeByYear = dbeNeedFeeByYear;
        this.dbePayFee = dbePayFee;
        this.dtePayDate = dtePayDate;
        this.dteStartTime = dteStartTime;
        this.dteEndTime = dteEndTime;
        this.intUser = intUser;
        this.strUserName = strUserName;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getIntAccountId() {
        return this.intAccountId;
    }
    
    public void setIntAccountId(Integer intAccountId) {
        this.intAccountId = intAccountId;
    }

    public Double getDbeNeedFeeByYear() {
        return this.dbeNeedFeeByYear;
    }
    
    public void setDbeNeedFeeByYear(Double dbeNeedFeeByYear) {
        this.dbeNeedFeeByYear = dbeNeedFeeByYear;
    }

    public Double getDbePayFee() {
        return this.dbePayFee;
    }
    
    public void setDbePayFee(Double dbePayFee) {
        this.dbePayFee = dbePayFee;
    }

    public Date getDtePayDate() {
        return this.dtePayDate;
    }
    
    public void setDtePayDate(Date dtePayDate) {
        this.dtePayDate = dtePayDate;
    }

    public Date getDteStartTime() {
        return this.dteStartTime;
    }
    
    public void setDteStartTime(Date dteStartTime) {
        this.dteStartTime = dteStartTime;
    }

    public Date getDteEndTime() {
        return this.dteEndTime;
    }
    
    public void setDteEndTime(Date dteEndTime) {
        this.dteEndTime = dteEndTime;
    }

    public Integer getIntUser() {
        return this.intUser;
    }
    
    public void setIntUser(Integer intUser) {
        this.intUser = intUser;
    }

    public String getStrUserName() {
        return this.strUserName;
    }
    
    public void setStrUserName(String strUserName) {
        this.strUserName = strUserName;
    }

	public String getStrDesc() {
		return strDesc;
	}

	public void setStrDesc(String strDesc) {
		this.strDesc = strDesc;
	}

	public Double getDbeAftResidual() {
		return dbeAftResidual;
	}

	public void setDbeAftResidual(Double dbeAftResidual) {
		this.dbeAftResidual = dbeAftResidual;
	}

	public Double getDbeCurResidual() {
		return dbeCurResidual;
	}

	public void setDbeCurResidual(Double dbeCurResidual) {
		this.dbeCurResidual = dbeCurResidual;
	}
   








}