package cn.insurance.model.right;



/**
 * TbRight generated by MyEclipse - Hibernate Tools
 */

public class TbRight  implements java.io.Serializable {

	private Integer id ;
	
	private String strName ;
	
	private int intRightType ;
	
	private String strDesc ;
	
	/**
	 * 保险公司的权限类型
	 */
	public static final int BX_RIGHT_TYPE = 1 ;
	
	/**
	 * 旅行社的权限类型
	 */
	public static final int LXS_RIGHT_TYPE = 2 ;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStrName() {
		return strName;
	}

	public void setStrName(String strName) {
		this.strName = strName;
	}

	public int getIntRightType() {
		return intRightType;
	}

	public void setIntRightType(int intRightType) {
		this.intRightType = intRightType;
	}

	public String getStrDesc() {
		return strDesc;
	}

	public void setStrDesc(String strDesc) {
		this.strDesc = strDesc;
	}







}